<% require "dotenv"; Dotenv.load(".env") %>

service: demo-deno-astro
image: gambala/demo-deno-astro
servers:
  - <%= ENV["MAIN_SERVER_IP"] %>
proxy:
  ssl: false
  host: deno-astro.gambala.pro
  app_port: 8085
  healthcheck:
    interval: 10
    path: /
registry:
  server: ghcr.io
  username: gambala
  password:
    - KAMAL_REGISTRY_PASSWORD
builder:
  arch: arm64
